# Generated by Django 3.0.4 on 2020-04-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('dob', models.CharField(max_length=12)),
                ('title', models.CharField(max_length=500)),
                ('Supervisor', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('image_url', models.CharField(max_length=500)),
            ],
        ),
    ]
